# Config File for {{{ Project }}}

default:
  projectName: {{{ Project }}}

# Config block for {{{ Block }}}

{{{ Block }}}:
  databaseName: {{{ Database }}}
  dbms: !expr keyring::key_get('{{{ Block }}}_dbms', keyring = '{{{ Project }}}')
  user: !expr keyring::key_get('{{{ Block }}}_user', keyring = '{{{ Project }}}')
  password: !expr keyring::key_get('{{{ Block }}}_password', keyring = '{{{ Project }}}')
  connectionString: !expr keyring::key_get('{{{ Block }}}_connectionString', keyring = '{{{ Project }}}')
  cdmDatabaseSchema: !expr keyring::key_get('{{{ Block }}}_cdmDatabaseSchema', keyring = '{{{ Project }}}')
  vocabDatabaseSchema: !expr keyring::key_get('{{{ Block }}}_vocabDatabaseSchema', keyring = '{{{ Project }}}')
  workDatabaseSchema: !expr keyring::key_get('{{{ Block }}}_workDatabaseSchema', keyring = '{{{ Project }}}')
  role: !expr keyring::key_get('{{{ Block }}}_role', keyring = '{{{ Project }}}')
  cohortTable: {{{ Cohort }}}
