---
title: {{{ Title }}}
subtitle: Evidence Generation Plan 
author: 
  - {{ Developer }}
date: Feburary 2, 1922
format:
  html:
    fontsize: 14pt
    number-sections: true
    number-depth: 3
    toc: true
    toc-location: left
    toc-depth: 2
    toc-title: Contents
    theme: cosmo
    grid:
      body-width: 2200px
      sidebar-width: 200px
      margin-width: 200px
      gutter-width: 50px
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Guidance Text [DELETE ME]

**PLEASE DELETE PRIOR TO PUBLISHING**

The purpose of the Evidence Generation Plan (EGP) is to lay out the assumptions of the data extraction and analysis strategy for a study. The EGP has five primary sections:

- **Background**: sets the scene for the analysis taking place; why is the study being conducted, what questions do we want to ask and on which data sources.
    - **Rationale**: the study rationale describes why the study is being executed. Is the study for a internal business purpose or is the intent to run a network safety study? The developer should describe the primary intent of the study within a paragraph. 
    - **Research Questions**: here we outline the high-level questions we wish to answer over the course of the analysis. Research questions should be written in bullets in a form of a question. 
    - **Data Sources**: which data sources are used in the analysis and why were they chosen. Provide a brief description of the date range of data capture, number of lives covered, geographic location and data type (e.g. claims, EHR, registry)
- **Cohort Definitions**: this section outlines the clinical logic needed to identify different patient populations. Cohorts can include the study population, drug exposure groups or study outcomes. 
- **Feasibility Assessment**: this section outlines assessments required to prior to the execution of the analysis. Examples include assessment of minimum study size or number of persons with a lab measure.
- **Analysis**: this section outlines the analytics that will be conducted in a study
- **Vulnerabilities**: this section outlines limitations and obstacles that would hinder the execution of the study.

# Background {#sec-background}

## Rationale {#sec-rationale}

**EXAMPLES PLEASE MODIFY**

The purpose of this study is to characterize patients with disease x for an internal analysis.

## Research Questions {#sec-questions}

**EXAMPLES PLEASE MODIFY**

- How many people can we identify with cohort 1?
- How do we characterize patients in cohort 1 at baseline (-365 days to -1 day before the index date)?

## Data Sources {#sec-data}


# Cohort Definitions {#sec-cohorts}

## Cohort 1: Disease X {#sec-cohort1}

### Cohort Entry

### Inclusion/Exclusion Criteria

### Cohort Exit

# Feasibility Assessment {#sec-feasibility}

## Cohort Counts

Our first feasibility for this analysis is to report the number of unique patients and occurrences identified among the cohorts listed in @sec-cohorts.  

# Analysis {#sec-analysis}

## Characterization {#sec-characterization}

The first portion of our analysis is to characterize the cohorts listed in @sec-cohorts. We describe demographics and baseline comorbidities where the baseline window is -365 days to -1 days prior to the index date of the cohort.

We report categorical variables by count and percentage and continuous variables by the mean, standard deviation, min, max, median, 25th and 75th percentiles.

### Demographics {#sec-demographics}

We report the following demographics for the cohorts listed in @sec-cohorts:

- Age (continuous and in 10 year groups)
- Gender
- Race (if available in the database)
- Year of index date
- Time in Cohort 

### Baseline Comorbidities {#sec-comorb}

For baseline comorbidities, we report the charlson comorbidity score and the proportion of patient with each category in the score. Below we show the comorbidities used in the Charlson with its accompanying point value:

- Acute Myocardial Infarction (1 point)  
- Congestive heart failure (1 point)   
- Peripheral vascular disease (1 point)   
- Cerebrovascular Disease (1 point)  
- Dementia (1 point)   
- Chronic pulmonary disease (1 point) 
- Mild liver disease (1 point)
- Rheumatologic disease (1 point)   
- Peptic ulcer disease (1 point)
- Diabetes (mild to moderate) (1 point)
- Hemiplegia or paraplegia (2 point)  
- Diabetes with chronic complications (2 point)
- Renal disease (2 point) 
- Any Malignancy (2 point)
- Moderate to severe liver disease (2 point)
- Metastatic solid tumor (6 point)
- AIDS (6 point)


# Vulnerabilities {#sec-vulnerabilities}


